### ISSUE TITLE
This project should be on pypi

### ISSUE THREAD

**Issue by chrisglass** [bmihelac/django-shop-discounts#1]
Hi there,

It'd be awesome if you could release this to pypi to ease installation.

Also, did you consider adding it to https://www.django-shop.org/en/ecosystem/ ?

Cheers,
- Chris

**Comment by bmihelac** [comment]
Thanks Chris, definetely I will. 

I think I would have to test it with some newer django-shop version before I do this.

**Comment by bmihelac** [comment]
sent into the wild world web
