### ISSUE TITLE
Release 0.0.7

### ISSUE THREAD

**Issue by bmihelac** [bmihelac/django-shop-discounts#10]
Check if it is compatible with django-shop 0.2.0 (see https://github.com/bmihelac/django-shop-discounts/pull/8)

Specify min django-shop version in requirements

```
require django-shop>=0.2.0
```

**Comment by bbirand** [comment]
Yes, I can confirm that this works under 0.2.0 for me

**Comment by bmihelac** [comment]
Thanks, I'll roll 0.0.7 ASAP.

**Comment by bbirand** [comment]
Thanks, that'd be great!

**Comment by bbirand** [comment]
Did you get to do this? I'm actually trying to deploy my code with these changes :)

**Comment by bmihelac** [comment]
https://pypi.python.org/pypi/django-shop-discounts/0.0.7

thanks for contribution!
