### ISSUE TITLE
Put discount code fields directly on the cart view

### ISSUE THREAD

**Issue by bbirand** [bmihelac/django-shop-discounts#12]
Right now, the way things are structured in the example app, there is a link that goes to a CreateView form for entering new codes. I think for most people, it makes more sense to have the field directly below the cart. When somebody submits the form, the cart page is shown again (as opposed to the address one), so that the user can see the effects of the code, or any errors in it.

Right now, I achieved this by overloading the get_context_data of my cart view (which is a subclass of the django-shop CartDetails):

``` python
class ShowCart(CartDetails):
    template_name = 'store/cart.html'

    def get_context_data(self, **kwargs):
        ''' Add a modelform for the DiscountCode for the promo code form
        '''
        # Get the current context data
        ctx= super(ShowCart,self).get_context_data(**kwargs)

        # update with the form object
        ctx.update({'form' : DiscountCodeForm()})

        # Put the errors also in the context of the cart
        ctx.update({'discount_code_error': self.request.session.get('discount_code_error', False)})

        # Once they are there, we can delete the session
        if self.request.session.get('discount_code_error', False):
            del self.request.session['discount_code_error']

        return ctx
```

I feel like this can easily be made into a view Mixin, to be used as:

``` python
class ShowCart(CartDetails, DiscountCodeMixin):
    template_name = 'store/cart.html'
```

I also have to save the errors in the session since I couldn't find a good way to pass them through the HttpResponseRedirect.

What do you think about this kind of use case? Should I submit a PR?

**Comment by bmihelac** [comment]
@bbirand I would like to have `CartDiscountCodeCreateView` handle ajax. For customisations where discount code form appears or redirects, it should be easy enough to override or replace `CartDiscountCodeCreateView` class. While mixin could be useful for some, it would mean more maintenance on the road.
