### ISSUE TITLE
Update code to reflect new BaseCartModifier methods parameters

### ISSUE THREAD

**Issue by yakky** [bmihelac/django-shop-discounts#7]
`request` has been added to many `BaseCartModifier` methods.
Code should be updated to accept new parameter

**Comment by bmihelac** [comment]
I saw (now closed) pull request https://github.com/bmihelac/django-shop-discounts/pull/5/files that added `request` arg to bunch of methods.

Can you check if code in that pull request works with latest django-shop?

**Comment by yakky** [comment]
Sure

**Comment by yakky** [comment]
Opened a new PR to fix some issues with #5

**Comment by bmihelac** [comment]
Thnaks a lot!
